#!/usr/sbin/nft -f

flush ruleset


table ip nat {
	chain postrouting {
	      type nat hook postrouting priority 100; policy accept;
	      oifname "enp6s0" masquerade
              }
}

table inet filter {
	chain input {
		type filter hook input priority 0; policy drop;
		ct state invalid counter drop comment "early drop of invalid packets"
		ct state {established, related} accept comment "acceptl all connections related to connections made by us"
		iif != lo ip daddr  127.0.0.1/8 drop comment "drop connections to loopback not coming from loopback"
		iif lo accept comment "accept loopback"
		ip protocol icmp counter accept comment "accept all ICMP types"

		#Allow DHCP and DNS on wlp5s0
		iifname "wlp5s0" udp dport { 67, 68, 53 } accept comment "Allow DHCP and DNS"
		iifname "wlp5s0" tcp dport 53 accept comment "Allow DNS (TCP)"

		#tcp dport 22 accept comment
		counter comment "count dropped packets"
		
		#Drop addresses
		ip saddr 54.151.255.151 drop
	}
chain forward {
		type filter hook forward priority 0; policy accept;
		counter comment "count dropped packets"
		iifname "wlp5s0" oifname "enp6s0" accept comment "Forward traffic from Hotspot to enp6s0"
		iifname  "enp6s0" oifname "wlp5s0" ct state established, related accept comment "Allow return traffic to Hotspot"
	}
	chain output {
		type filter hook output priority 0; policy accept;
		counter comment "count accepted packets"
	}
}


